
#        ________ _______ _______ _____  _______ ________ _______      _______ _______ _____
#        |  |  |  |_     _|    |  |     \|       |  |  |  |     __|    |   _   |    |  |     \
#        |  |  |  |_|   |_|       |  --  |   -   |  |  |  |__     |    |       |       |  --  |
#        |________|_______|__|____|_____/|_______|________|_______|    |___|___|__|____|_____/
#
#        ________ _______ ______ __  __ _______ ______ _______ ______ _______
#        |  |  |  |       |   __ \  |/  |     __|   __ \   _   |      |    ___|
#        |  |  |  |   -   |      <     <|__     |    __/       |   ---|    ___|
#        |________|_______|___|__|__|\__|_______|___|  |___|___|______|_______|
#                                 config by kazro

# ---------- windows and workspace ----------

windowrule {
    # Ignore maximize requests from all apps. You'll probably like this.
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
    persistent_size = on
}

dwindle {
    pseudotile = true
    preserve_split = true
}

master {
    new_status = master
}

windowrule = opacity 0.99, match:class obsidian
windowrule = opacity 0.99, match:class zen
