
#         _______ ___ ___ ______ ______ _____   _______ _______ _____
#        |   |   |   |   |   __ \   __ \     |_|   _   |    |  |     \
#        |       |\     /|    __/      <       |       |       |  --  |
#        |___|___| |___| |___|  |___|__|_______|___|___|__|____|_____/
#                              config by kazro


# ---------- sources / imports ----------

source = ./modules/*


# ---------- Monitors ----------

monitor=,preferred,auto, 1

xwayland {
  force_zero_scaling = true
}


# ---------- environment variables ----------

env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24
env = LIBVA_DRIVER_NAME,nvidia
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = QT_QPA_PLATFORMTHEME,qt5ct
env = QT_STYLE_OVERRIDE,kvantum
env = ELECTRON_OZONE_PLATFORM_HINT,auto


# ---------- input ----------

input {
    kb_layout = us
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =

    follow_mouse = 1

    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.

    touchpad {
        natural_scroll = true
        scroll_factor = 1
    }
}

gesture = 3, horizontal, workspace

device {
    name = epic-mouse-v1
    sensitivity = -0.5
}
